const splideProps = {
    type: {type: String},
    rewind: {type: Boolean},
    speed: {type: Number},
    rewindSpeed: {type: Number},
    width: {type: Number|String},
    height: {type: Number|String},
    fixedWidth: {type: Number|String},
    fixedHeight: {type: Number|String},
    heightRatio: {type: Number},
    autoWidth: {type: Boolean},
    autoHeight: {type: Boolean},
    start: {type: Number},
    perPage: {type: Number},
    perMove: {type: Number},
    clones: {type: Number},
    cloneStatus: {type: Boolean},
    focus: {type: Number|'center'},
    gap: {type: Number|String},
    padding: {type: Number|String|{left: Number|String, right: Number|String}|{top: Number|String, bottom: Number|String}},
    arrows: {type: Boolean|'slider'},
    pagination: {type: Boolean|'slider'},
    easing: {type: String},
    easingFunc: {type: Function},
    drag: {type: Boolean|'free'},
    noDrag: {type: String},
    dragMinThreshold: {type: Number|{ mouse: Number, touch: Number }},
    flickPower: {type: Number},
    flickMaxPages: {type: Number},
    waitForTransition: {type: Boolean},
    arrowPath: {type: String},
    autoplay: {type: Boolean | 'pause'},
    interval: {type: Number},
    pauseOnHover: {type: Boolean},
    pauseOnFocus: {type: Boolean},
    resetProgress: {type: Boolean},
    lazyLoad: {type: Boolean | 'nearby' | 'sequential' },
    preloadPages: {type: Number},
    keyboard: {type: Boolean|'focused'},
    wheel: {type: Boolean},
    releaseWheel: {type: Boolean},
    direction: {type: 'ltr' | 'rtl' | 'ttb'},
    cover: {type: Boolean},
    slideFocus: {type: Boolean},
    focusableNodes: {type: String},
    isNavigation: {type: Boolean},
    trimSpace: {type: Boolean|'move'},
    updateOnMove: {type: Boolean},
    mediaQuery: {type: 'min' | 'max'},
    breakpoints: {type: Object},
    classes: {type: Object},
    i18n: {type: Object},
    destroy: {type: Boolean|'completely'}
}

export default splideProps;